{% set name = "optopHyre" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optophyre-{{ version }}.tar.gz
  sha256: 19aa8e30bb3e7993feefb5c056a73317e3fe332daca3ee35147821a366a8fc0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas

test:
  imports:
    - optopHyre
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'optopHyre: processing optode datasets from Pyroscience sensors'
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/optopHyre

extra:
  recipe-maintainers:
    - mvdh7
